#ifndef ANIME_DM_RESOURCE_H
#define ANIME_DM_RESOURCE_H

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ADD_DOWNLOAD 200
#define IDC_ADD_SOURCE 201
#define IDC_ADD_URL 202
#define IDC_ADD_FETCH 203
#define IDC_ADD_EPISODES 204
#define IDC_ADD_DEST 205
#define IDC_ADD_BROWSE 206

#define IDD_ABOUT 210
#define IDD_SHORTCUTS 211

#define IDD_SETTINGS 220
#define IDC_SET_LANG 221
#define IDC_SET_THEME 222
#define IDC_SET_FOLDER_ICONS 223
#define IDC_SET_TEMPLATE 224
#define IDC_SET_DLDIR 225
#define IDC_SET_BROWSE 226

#define IDD_SEARCH 230
#define IDC_SEARCH_QUERY 231
#define IDC_SEARCH_SCOPE 232
#define IDC_SEARCH_RESULTS 233

#endif
