#include "ui/Strings.h"

#include <windows.h>

namespace {

struct Translation {
    const wchar_t* fr;
    const wchar_t* en;
};

// Every user-visible string, in declaration order of the StringId enum.
constexpr Translation kTable[STR_COUNT] = {
    {L"Tâches", L"Tasks"},
    {L"Fichier", L"File"},
    {L"Téléchargement", L"Downloads"},
    {L"Affichage", L"View"},
    {L"Aide", L"Help"},

    {L"Ajout URL\tCtrl+N", L"Add URL\tCtrl+N"},
    {L"Téléchargement manuel", L"Manual download"},
    {L"Téléchargement par lot depuis presse-papiers\tCtrl+Maj+V",
     L"Batch download from clipboard\tCtrl+Shift+V"},
    {L"Exporter", L"Export"},
    {L"Importer", L"Import"},
    {L"Vers un fichier d'exportation d'ADM", L"To an ADM export file"},
    {L"Vers un fichier texte (.txt)", L"To a text file (.txt)"},
    {L"Vers un fichier JSON (.json)", L"To a JSON file (.json)"},
    {L"Vers un tableur (.xlsx, .csv, .ods)", L"To a spreadsheet (.xlsx, .csv, .ods)"},
    {L"Depuis un fichier d'exportation d'ADM", L"From an ADM export file"},
    {L"Depuis un fichier texte (.txt)", L"From a text file (.txt)"},
    {L"Depuis un fichier JSON (.json)", L"From a JSON file (.json)"},
    {L"Depuis un tableur (.xlsx, .csv, .ods)", L"From a spreadsheet (.xlsx, .csv, .ods)"},
    {L"Quitter", L"Quit"},

    {L"Démarrer le téléchargement", L"Start download"},
    {L"Arrêter le téléchargement", L"Stop download"},
    {L"Re-télécharger", L"Redownload"},
    {L"Supprimer\tSuppr", L"Delete\tDel"},

    {L"Tout arrêter", L"Stop all"},
    {L"Supprimer les terminés", L"Remove completed"},
    {L"Tout supprimer", L"Delete all"},
    {L"Rechercher\tCtrl+F", L"Find\tCtrl+F"},
    {L"Planifier", L"Schedule"},
    {L"Démarrer file d'attente", L"Start queue"},
    {L"Arrêter file d'attente", L"Stop queue"},
    {L"File principale", L"Main queue"},
    {L"File du planificateur", L"Scheduler queue"},
    {L"Limiteur de vitesse", L"Speed limiter"},
    {L"Activer", L"Enable"},
    {L"Désactiver", L"Disable"},
    {L"Paramètres", L"Settings"},
    {L"Booster de vitesse", L"Speed booster"},

    {L"Addon Store", L"Addon Store"},
    {L"Panneau Catégories", L"Categories panel"},
    {L"Classer les fichiers", L"Sort files"},
    {L"Par ordre d'ajout", L"By date added"},
    {L"Par nom de fichier", L"By file name"},
    {L"Par taille", L"By size"},
    {L"Par statut", L"By status"},
    {L"Par temps restant", L"By time left"},
    {L"Par vitesse", L"By speed"},
    {L"Par date du dernier essai", L"By last try"},
    {L"Par emplacement", L"By location"},
    {L"Par adresse", L"By address"},
    {L"Par page web parente", L"By parent page"},
    {L"Barre d'outils", L"Toolbar"},
    {L"Icônes système (Segoe Fluent)", L"System icons (Segoe Fluent)"},
    {L"Aucune peau dans le dossier toolbar", L"No skin in the toolbar folder"},
    {L"Personnaliser les colonnes", L"Customise columns"},
    {L"Mode", L"Mode"},
    {L"Sombre", L"Dark"},
    {L"Claire", L"Light"},
    {L"Système", L"System"},
    {L"Police", L"Font"},
    {L"Sélectionner la police", L"Select the font"},
    {L"Rétablir la police par défaut", L"Reset the default font"},
    {L"Langue", L"Language"},

    {L"Aide\tF1", L"Help\tF1"},
    {L"Raccourcis", L"Shortcuts"},
    {L"Mise à jour rapide", L"Quick update"},
    {L"À propos", L"About"},
    {L"Auteurs", L"Authors"},
    {L"Licence", L"Licence"},
    {L"Crédits", L"Credits"},

    {L"Ajout URL", L"Add URL"},
    {L"Reprendre", L"Resume"},
    {L"Arrêter", L"Stop"},
    {L"Tout arrêter", L"Stop all"},
    {L"Supprimer", L"Delete"},
    {L"Tout supprimer", L"Delete all"},
    {L"Options", L"Options"},
    {L"Planifier", L"Schedule"},
    {L"Addons", L"Addons"},
    {L"Rechercher", L"Find"},

    {L"Nom du fichier", L"File name"},
    {L"Taille", L"Size"},
    {L"Statut", L"Status"},
    {L"Temps restant", L"Time left"},
    {L"Débit de téléchargement", L"Download speed"},
    {L"Date du dernier essai", L"Last try date"},
    {L"Date d'ajout", L"Date added"},

    {L"Nom", L"Name"},
    {L"Langue", L"Language"},
    {L"Version", L"Version"},
    {L"Statut", L"Status"},
    {L"Actualiser", L"Refresh"},
    {L"Installer", L"Install"},
    {L"Mettre à jour", L"Update"},
    {L"Supprimer", L"Remove"},
    {L"Configurer", L"Configure"},
    {L"Chargement…", L"Loading…"},
    {L"Installé", L"Installed"},
    {L"Disponible", L"Available"},
    {L"Mise à jour disponible", L"Update available"},
    {L"Aucune extension", L"No extension"},
    {L"Le magasin est injoignable.", L"The store cannot be reached."},
    {L"L'installation a échoué.", L"The installation failed."},
    {L"La suppression a échoué.", L"The removal failed."},
    {L"Configuration", L"Settings"},
    {L"Cette extension ne déclare aucun réglage.",
     L"This extension declares no setting."},
    {L"Aucune source installée", L"No source installed"},
    {L"Le chargement a échoué.", L"The loading failed."},
    {L"Titre", L"Title"},
    {L"En attente", L"Pending"},
    {L"Lecteur :", L"Player:"},
    {L"Auto", L"Auto"},
    {L"Texte", L"Text"},
    {L"Liste", L"List"},
    {L"Tout", L"All"},
    {L"Aucun", L"None"},
    {L"%d épisode(s)", L"%d episode(s)"},
    {L"Télécharger (%d)", L"Download (%d)"},
    {L"ex : 1-20  ·  1,5,8", L"e.g. 1-20  ·  1,5,8"},
    {L"Clic droit sur un épisode pour changer son lecteur.",
     L"Right-click an episode to change its player."},
    {L"Chargement des lecteurs…", L"Loading the players…"},
    {L"Aucun lecteur", L"No player"},
    {L"Affiche", L"Cover"},
    {L"Enregistrer l'image", L"Save the image"},
    {L"Image enregistrée.", L"Image saved."},

    {L"Catégories", L"Categories"},
    {L"Tous les animés", L"All anime"},
    {L"File d'attente", L"Queue"},

    {L"Information", L"Notice"},
    {L"« %s » : à venir", L"“%s”: coming soon"},

    {L"Ouvrir", L"Open"},
    {L"Ouvrir le dossier", L"Open folder"},

    {L"Ajouter un téléchargement", L"Add a download"},
    {L"Source :", L"Source:"},
    {L"URL de l'animé :", L"Anime URL:"},
    {L"Valider", L"Confirm"},
    {L"Épisodes :", L"Episodes:"},
    {L"Destination :", L"Destination:"},
    {L"Télécharger", L"Download"},
    {L"Configuration d'Anime Download Manager", L"Anime Download Manager configuration"},
    {L"Icônes de dossier", L"Folder icons"},
    {L"Appliquer une icône au dossier de chaque animé", L"Apply an icon to each anime's folder"},
    {L"Modèle de design :", L"Design template:"},
    {L"Compatibilité Aniyomi", L"Aniyomi compatibility"},
    {L"Adapter automatiquement chaque nouvel animé pour Aniyomi (cover.jpg + .nomedia)",
     L"Automatically adapt each new anime for Aniyomi (cover.jpg + .nomedia)"},
    {L"Terminé", L"Done"},
    {L"Général", L"General"},
    {L"Enregistrer sous", L"Save to"},
    {L"Téléchargements", L"Downloads"},
    {L"Intégration au navigateur / Système", L"Browser / System integration"},
    {L"Lancer Anime Download Manager à l'ouverture de session",
     L"Start Anime Download Manager when signing in"},
    {L"Intégration aux navigateurs suivants :", L"Integrate with the following browsers:"},
    {L"L'extension doit être installée dans chaque navigateur coché.",
     L"The extension must be installed in each checked browser."},
    {L"Dossier de téléchargement", L"Download folder"},
    {L"Proposer ce dossier à chaque nouvel ajout", L"Offer this folder for every new download"},
    {L"Téléchargements simultanés :", L"Simultaneous downloads:"},
    {L"Connexions par téléchargement :", L"Connections per download:"},
    {L"Un nombre de téléchargements plus large s'applique aussitôt ; le nombre de connexions "
     L"vaut pour les prochains transferts.",
     L"A wider download count applies at once; the connection count holds for the next "
     L"transfers."},
    {L"Panneau de téléchargement dans les navigateurs :", L"Download panel in the browsers:"},
    {L"Éditer…", L"Edit…"},
    {L"Installer l'extension…", L"Install the extension…"},
    {L"Personnalisation du panneau de téléchargement", L"Download panel customisation"},
    {L"Aspect du panneau :", L"Look of the panel:"},
    {L"Mode complet", L"Full mode"},
    {L"Mode mini", L"Mini mode"},
    {L"L'afficher :", L"Show it:"},
    {L"Sur la page d'un animé ou d'un épisode", L"On the page of an anime or an episode"},
    {L"Au survol d'un lien vers un animé ou un épisode",
     L"Over a link that leads to an anime or an episode"},
    {L"Télécharger avec ADM", L"Download with ADM"},
    {L"Rechercher", L"Find"},
    {L"Rechercher :", L"Find:"},
    {L"Dans :", L"In:"},
    {L"Rechercher", L"Find"},
    {L"Tout", L"Everything"},
    {L"Nom du fichier", L"File name"},
    {L"Animé", L"Anime"},
    {L"Adresse", L"Address"},
    {L"Animé", L"Anime"},
    {L"À propos", L"About"},
    {L"Gestionnaire de téléchargement d'animés pour Windows (C++ / Win32).",
     L"Anime download manager for Windows (C++ / Win32)."},
    {L"Raccourcis clavier", L"Keyboard shortcuts"},
    {L"Ajouter un téléchargement", L"Add a download"},
    {L"Supprimer la sélection", L"Delete the selection"},
    {L"Rechercher", L"Find"},
    {L"Téléchargement par lot", L"Batch download"},
    {L"Aide", L"Help"},
    {L"Fermer la boîte de dialogue", L"Close the dialog"},
    {L"Suppr", L"Del"},
    {L"Ctrl + Maj + V", L"Ctrl + Shift + V"},
    {L"Échap", L"Esc"},
    {L"Parcourir...", L"Browse..."},
    {L"OK", L"OK"},
    {L"Annuler", L"Cancel"},
    {L"Fermer", L"Close"},

    {L"Résolution", L"Resolving"},
    {L"Téléchargement", L"Downloading"},
    {L"Assemblage", L"Assembling"},
    {L"Terminé", L"Completed"},
    {L"Échec", L"Failed"},
    {L"Arrêté", L"Stopped"},
    {L"démarrage…", L"starting…"},
    {L"la source n'a pas répondu", L"the source did not answer"},
    {L"aucun lecteur sur cet épisode", L"no player on this episode"},
    {L"aucune vidéo exploitable", L"no usable video"},
    {L"la connexion a été perdue", L"the connection was lost"},
    {L"la liste de lecture est illisible", L"the playlist cannot be read"},
    {L"la clé de déchiffrement est illisible", L"the decryption key cannot be read"},
    {L"l'écriture sur le disque a échoué", L"writing to the disk failed"},
    {L"Tout arrêter", L"Stop all"},
    {L"Arrêter tous les téléchargements en cours ?", L"Stop every running download?"},
    {L"Tout supprimer", L"Delete all"},
    {L"Supprimer tous les téléchargements de la liste ? Les téléchargements en cours "
     L"seront arrêtés.",
     L"Remove every download from the list? The running ones will be stopped."},
    {L"Confirmer la suppression", L"Confirm the removal"},
    {L"Supprimer les téléchargements sélectionnés ?", L"Remove the selected downloads?"},
    {L"Supprimer aussi les fichiers téléchargés du disque.",
     L"Also delete the downloaded files from the disk."},
    {L"%d téléchargement(s) terminé(s) retiré(s).", L"%d completed download(s) removed."},
    {L"Le fichier n'est pas encore disponible.", L"The file is not available yet."},
    {L"Aucun téléchargement sélectionné.", L"No download selected."},

    {L"Film", L"Movie"},
    {L"Supprimer l'animé", L"Delete the anime"},
    {L"Supprimer l'animé", L"Delete the anime"},
    {L"Confirmer la suppression de « %s » ?", L"Confirm the deletion of \"%s\"?"},
    {L"Le fichier a été déplacé ou supprimé.", L"The file was moved or deleted."},
    {L"Le dossier a été déplacé, renommé ou supprimé.",
     L"The folder was moved, renamed or deleted."},

    {L"Icône du dossier :", L"Folder icon:"},
    {L"(modèle par défaut)", L"(default template)"},
    {L"Changer le modèle d'icône", L"Change the icon template"},
    {L"Icône appliquée.", L"Icon applied."},
    {L"Aucun dossier pour cet animé.", L"No folder for this anime."},
    {L"ImageMagick est introuvable : installez-le pour que la commande magick soit disponible.",
     L"ImageMagick cannot be found: install it so the magick command is available."},
    {L"Les calques des gabarits sont introuvables à côté de l'application.",
     L"The template layers cannot be found next to the application."},
    {L"La génération de l'icône a échoué.", L"The icon could not be generated."},
    {L"Adapter pour Aniyomi", L"Adapt for Aniyomi"},
    {L"Dossier adapté pour Aniyomi.", L"Folder adapted for Aniyomi."},
    {L"Affiche brute", L"Raw poster"},
    {L"Ombre seule", L"Shadow only"},
    {L"Boîtier Blu-ray", L"Blu-ray case"},
    {L"Dossier horizontal", L"Horizontal folder"},
    {L"Dossier vertical", L"Vertical folder"},
    {L"Boîtier plastique transparent", L"Clear plastic case"},
    {L"Boîtier DVD sombre", L"Dark DVD box"},
    {L"Boîtier DVD clair", L"Light DVD box"},
    {L"Windows 11", L"Windows 11"},
    {L"BeOrigin (style macOS)", L"BeOrigin (macOS style)"},
    {L"Disque", L"Disc"},
    {L"Double onglet vertical", L"Vertical dual tab"},
    {L"Adresse", L"Address"},
    {L"Source", L"Source"},
    {L"Info sur le téléchargement", L"Download information"},
    {L"Épisodes à télécharger", L"Episodes to download"},
    {L"URL", L"URL"},
    {L"Enregistrer sous", L"Save to"},
    {L"Rappeler ce chemin", L"Remember this path"},
    {L"Plus tard", L"Later"},
    {L"Démarrer", L"Start"},
    {L"%d épisode(s) sur %d", L"%d of %d episode(s)"},
    {L"Saisissez l'adresse d'un animé.", L"Enter the address of an anime."},
    {L"Cette adresse ne semble pas venir de la source choisie. Continuer quand même ?",
     L"This address does not seem to come from the chosen source. Continue anyway?"},
    {L"Presse-papiers", L"Clipboard"},
    {L"Coller le lien du presse-papiers à l'ouverture de la fenêtre d'ajout",
     L"Paste the link of the clipboard when the add window opens"},
    {L"Sélection :", L"Selection:"},
    {L"Automatique (au choix de la source)", L"Automatic (the source decides)"},
    {L"Lecteurs connus après un premier essai", L"Players known after a first try"},
    {L"Mettre dans la file", L"Move to the queue"},
    {L"Planificateur", L"Scheduler"},
    {L"File :", L"Queue:"},
    {L"Démarrer cette file automatiquement", L"Start this queue on its own"},
    {L"Une fois, le", L"Once, on"},
    {L"Chaque jour :", L"Every day:"},
    {L"Lun|Mar|Mer|Jeu|Ven|Sam|Dim", L"Mon|Tue|Wed|Thu|Fri|Sat|Sun"},
    {L"Démarrer à", L"Start at"},
    {L"Arrêter la file à", L"Stop the queue at"},
    {L"Une fois la file terminée :", L"Once the queue is done:"},
    {L"Ne rien faire", L"Do nothing"},
    {L"Quitter Anime Download Manager", L"Quit Anime Download Manager"},
    {L"Éteindre l'ordinateur", L"Shut down the computer"},
    {L"Fichiers de la file :", L"Files in the queue:"},
    {L"Démarrer maintenant", L"Start now"},
    {L"Arrêter la file", L"Stop the queue"},
    {L"(aucun fichier dans cette file)", L"(no file in this queue)"},
    {L"Files", L"Queues"},
    {L"Animés suivis", L"Followed animes"},
    {L"Les nouveaux épisodes de ces animés sont ajoutés d'eux-mêmes, vérifiés le jour de "
     L"sortie puis toutes les trois heures pendant deux jours.",
     L"New episodes of these animes are added on their own, checked on the release day and "
     L"then every three hours for two days."},
    {L"Animé", L"Anime"},
    {L"Dernier paru", L"Last released"},
    {L"Sortie", L"Release"},
    {L"Prochaine vérification", L"Next check"},
    {L"Suivre un animé…", L"Follow an anime…"},
    {L"Modifier…", L"Edit…"},
    {L"Vérifier maintenant", L"Check now"},
    {L"Retirer", L"Remove"},
    {L"(aucun animé suivi)", L"(no anime followed)"},
    {L"aucun encore", L"none yet"},
    {L"dès que possible", L"as soon as possible"},
    {L"Suivre un animé", L"Follow an anime"},
    {L"Animé", L"Anime"},
    {L"Jour de sortie", L"Release day"},
    {L"Heure", L"Time"},
    {L"File", L"Queue"},
    {L"Démarrer les nouveaux épisodes aussitôt", L"Start the new episodes at once"},
    {L"Les épisodes déjà listés ne sont pas repris : seuls ceux qui paraîtront ensuite "
     L"seront ajoutés, dans le dossier de l'animé.",
     L"The episodes already listed are not fetched again: only those released from now on "
     L"are added, into the folder of the anime."},
    {L"Suivre les nouveaux épisodes…", L"Follow the new episodes…"},
    {L"Lundi|Mardi|Mercredi|Jeudi|Vendredi|Samedi|Dimanche",
     L"Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday"},
    {L"%d résultat(s)", L"%d result(s)"},
    {L"Double-clic ou Entrée : afficher dans la liste", L"Double-click or Enter: show in the list"},
};

Language g_language = Language::French;

}  // namespace

// Switches the active language for every later lookup.
void SetLanguage(Language language) {
    g_language = language;
}

// Returns the currently active language.
Language ActiveLanguage() {
    return g_language;
}

// Returns the string for the active language.
const wchar_t* Str(StringId id) {
    const Translation& entry = kTable[id];
    return g_language == Language::English ? entry.en : entry.fr;
}

// Applies a translated caption to a dialog control.
void SetDialogText(void* dialog, int controlId, StringId id) {
    SetDlgItemTextW(static_cast<HWND>(dialog), controlId, Str(id));
}

// Applies a translated caption to a dialog window.
void SetDialogTitle(void* dialog, StringId id) {
    SetWindowTextW(static_cast<HWND>(dialog), Str(id));
}
